#pragma once

#define MAX_NUM_ENTITIES 1024
#define MAX_LOADABLE_TEXTURES 128
#define TARGET_FPS_FRAMETIME_FLOAT (1.0f / 60.0f)
#define MAX_LIGHT_COUNT 16

#define LIGHT_DIRECTIONAL 0
#define LIGHT_POINT 1
#define LIGHT_SPOT 2