#pragma once

#ifndef AAAAAAAAAAAAAAPCH_H
#define AAAAAAAAAAAAAAPCH_H

#ifndef TINYGLTF_IMPLEMENTATION
#define TINYGLTF_IMPLEMENTATION
#endif

#ifndef STB_IMAGE_IMPLEMENTATION
#define STB_IMAGE_IMPLEMENTATION
#endif

#ifndef STB_IMAGE_WRITE_IMPLEMENTATION
#define STB_IMAGE_WRITE_IMPLEMENTATION
#endif

#include <filesystem>
#include <External/tiny_gltf.h>

#endif //AAAAAAAAAAAAAAPCH_H